config/routes.rb
GuDa::Application.routes.draw do
  root :to => 'blog#index'
  get "blog" => 'blog#index'
  get "blog/logout" => "blog#logout", as: :logout
  get "/auth/:provider/callback", :to => "authentications#create"
  get "/auth/failure", :to => "authentications#index"
  get "/articles/demonew", :to => "articles#demonew"
  get "/articles/demoshow", :to => "articles#demoshow"

  #scope 'blog' do
  resources :users do
    resources :articles do
      resources :comments
    end
    resources :drafts
    collection do 
      post :login
      post :new
      get :new
    end
    resources :notifications, :only => [:index, :show, :destroy] 
    resources :settings
    resources :authentications
    resources :catagories
    resources :pictures
  end
 
  resources :pages
  resources :pictures, :only => [:create, :destroy]
  resources :admins
  resources :articles do
    resources :comments
  end
  resources :drafts
  resources :catagories
  resources :tags
  resources :notifications
  resources :authentications do
    collection do
      post :share
    end
  end
  post "users/login" => 'users#login', :as => :login 

#  end
  get ':user_id', :to => 'articles#index', :as => :name
  #match ':controller(/:action(/:id(.:format)))'  
end

app/views/admins/index.html.erb
<% content_for :other_js do|c|%>
<%end%>

<h3><%= "管理员 #{@user.nickname}"%></h3>
<div class="page_div">
  <h4>静态页面</h4>
  <%= link_to "新建", new_page_path, class:'btn btn-warning pull-right' %> 
  <table class='table' >
    <tr>
      <th>#</th>
      <th>title</th>
      <th>操作</th>
    </tr>

    <% @pages.each do|p|%>
      <tr>
        <td> <%= p.id %> </td>
        <td> <%= link_to "#{p.title}(#{p.subtitle})", page_path(p) %>  </td>
        <td> <%= link_to "编辑", edit_page_path(p) %>|<%= link_to '删除', page_path(p), method: :delete %>  </td>
      </tr>
    <%end%>
  </table>
</div>

app/views/admins/show.html.erb
<%= javascript_include_tag "pic" %>
<h1><%= "管理员 #{@user.nickname}"%></h1>

<div id="index_images">
  <%if @pages['index_images']%>
    <% @pages['index_images'].pictures.each do|p| %>
      <img src="<%= p.file.small.url%>" />
    <%end%>
  <%end%>
  <%= simple_form_for @pages['index_images'] || Page.new(title:"index_images"), :url => "/pages", :remote => true, :html => {:id=> "index_images_form"} do|f| %>
    <%= f.input :title, as: :hidden%>
    <%= f.input :pictures, :as => :file, input_html:{name:"page[pictures][1]"}, label:false%> 
    <%= f.input :pictures, :as => :file, input_html:{name:"page[pictures][2]"}, label:false%> 
    <%= f.button :submit, '确定', :class => 'btn btn-primary' %>
  <%end%>
</div>

<%= debug @pages %>