config/routes.rb
GuDa::Application.routes.draw do
  root :to => 'blog#index'
  get "blog" => 'blog#index'
  get "blog/logout" => "blog#logout", as: :logout
  get "/auth/:provider/callback", :to => "authentications#create"
  get "/auth/failure", :to => "authentications#index"
  get "/articles/demonew", :to => "articles#demonew"
  get "/articles/demoshow", :to => "articles#demoshow"

  #scope 'blog' do
  resources :users do
    resources :articles do
      resources :comments
    end
    resources :drafts
    collection do 
      post :login
      post :new
      get :new
    end
    resources :notifications, :only => [:index, :show, :destroy] 
    resources :settings
    resources :authentications
    resources :catagories
    resources :pictures
  end
 
  resources :pages
  resources :pictures, :only => [:create, :destroy]
  resources :admins
  resources :articles do
    resources :comments
  end
  resources :drafts
  resources :catagories
  resources :tags
  resources :notifications
  resources :authentications do
    collection do
      post :share
    end
  end
  post "users/login" => 'users#login', :as => :login 

#  end
  get ':user_id', :to => 'articles#index', :as => :name
  #match ':controller(/:action(/:id(.:format)))'  
end

app/models/article.rb
# encoding: UTF-8
require_dependency 'jas/jredis_counter'
class Article < ActiveRecord::Base
  paginates_per 10 
  belongs_to :user
  belongs_to :catagory
  has_many :article_tagships
  has_many :tags, through: :article_tagships 
  has_many :comments, dependent: :destroy 
  has_many :pictures, as: :pictureable, dependent: :destroy 
  has_many :notifications, as: :senderable

  include Redis::Objects
  include JCounter
  jcounter :visit
  counter :comments_count

  attr_accessor :picture

  validates :user_id, presence: {message: '用户id不能为空' }
  validates :title, presence: { message: '题目不能为空' }#, :length=>{ :minimum=>5, :maximum=>100, :message => '题目长度在6-20之间'  } 
  validates :content, presence: { message: '内容不能为空' }

  before_save :set_preview 

  def self.get_index(user_id, page=1)
    includes(:catagory).select("id, visit, preview, updated_at, created_at, title, user_id, catagory_id").where("user_id=?", user_id).order("created_at desc").page(page)
  end

  def self.catagory_index(user_id=nil, catagory_id=0, page=1)
    if user_id
      articles = Article.select("id, visit, updated_at, user_id, catagory_id, preview, created_at, title").where("user_id=? and catagory_id = ?", user_id, catagory_id).order("created_at desc").page(page)
    else
      articles = Article.select("id, visit,updated_at, user_id, catagory_id, preview, created_at, title").where("catagory_id=?", catagory_id).order("created_at desc").page(page)
    end
    articles
  end
  
  def catagory
    c = super
    unless c
      c = Catagory.default(self.user_id)
    end
    c
  end

  def markdown_content
    MarkdownTopicConverter.format(content)
  end

  private
  def set_preview
    max_word_count = 800 
    if self.content.length > max_word_count
      self.preview = "#{self.content.first(max_word_count)}..." #为文章内容加入preview
    else
      self.preview = self.content
    end
  end

end

app/controllers/articles_controller.rb
# encoding: UTF-8
class ArticlesController < ApplicationController
  layout "article"
  before_filter :check_login, :only => [:edit, :create, :new, :update, :destroy]   
  before_filter :check_session
  before_filter {|c| c.set_breadcrumbs}
  before_filter :init_params, :only => [:create, :update]
  # TODO: 文章图片(初步完成 添加 删除 ajax滚动读取)
  # TODO: preview 滚动问题
  # TODO: demo完善
  # TODO: 分页
  # TODO: catagory重构删除加data-confirm
  # TODO: 错误处理
  # TODO: preview显示添加的图片的时候可以remove走同时 remove掉 textarea里面的链接
  # TODO: page model controller view 更加细化
  # TODO: 删减一下bootstrap css里面用不到的东西例如图标自体那些
  # TODO: 美化article_index 分页导航
  # TODO: 增加回复别人评论时候notify一下的功能，要大修了, 还有全站ajax获取有没有新notify
  # TODO: windjs
  # TODO: notify画面可以直接回复
  # TODO: 关注用户，用户更新有notify功能
  # TODO: ssl通道, 上线后再处理
  # TODO: 每个blog要有加banner功能
  # TODO: 头像可切割
  # TODO: 文章追加功能
  # TODO: 小工具， todo list
  # TODO: 草稿功能能保存到服务器
  # TODO: 模板功能
  
  def index
    params[:user_id] = session[:user_id] if params[:user_id].blank?
    @current_user = User.get_user(params)
    unless @current_user
      redirect_to root_path, alert:'没有这个用户'
      return
    end
    respond_to do |format|
      format.html do 
        @articles = Article.get_index(@current_user.id, params[:page])
        if session[:signup_new] || @articles.size == 0 #新注册进来产生一些提示操作的变量
          session[:signup_new] = nil
          @signup_new = true
        end
        set_catagories(@current_user.id)
        drop_breadcrumbs {@current_user}
        check_owner(@current_user)
      end

      format.atom do
        @articles = Article.where("user_id=?", @current_user.id).order("created_at desc")
        @updated = @articles.size > 0 ? @articles.first.updated_at : nil
        @title = @current_user.blog_name
        render layout: false
      end
    end
  end

  def new
    @article = Article.new(user_id: session[:user_id])
    @current_user = User.by_id(session[:user_id])
    set_catagories(session[:user_id])
    set_page_title '新建文章',@current_user
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = @user_id
    if @article.save
      flash[:notice]='文章创建成功！'
      cookies[:create_article] = @article.id 
      redirect_to article_path(@article)  
    else
      flash[:error] = "出错了:#{@article.jerrors}"
      set_catagories(@user_id)
      render :new
    end
  end

  def edit
    @article = Article.find_by_id(params[:id])
    @catagories = Catagory.get_all(session[:user_id])
    @current_user = User.by_id(session[:user_id])
    set_page_title "修改文章|#{@article.title}", @current_user
  end

  def update
    @article = Article.find_by_id(params[:id])
    if @article.update_attributes(article_params)
      cookies[:update_article] = @article.id
      redirect_to @article, notice: '编辑成功'
    else
      flash[:error] = @article.jerrors
      render :action => 'edit' 
    end
  end

  def show
    @article = Article.find(params[:id])
    @article.visit_key.increment
    @current_user = User.by_id(@article.user_id)
    @user = User.find(session[:user_id]) if session[:user_id]
    @comments = Comment.get_by_article_id(@article.id)
    set_catagories(@article.user_id)
    set_page_title( @article.title, @current_user)
    check_owner @current_user
    respond_to do|format|
      format.html
      format.json {render json: @article.to_json }
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if check_owner(@article.user)
      @article.destroy
      respond_to do |format|
        format.html { redirect_to articles_url }
        format.json { head :ok }
      end
    else
      flash[:error]= '当前用户没有权限删除！'
      redirect_to root_path
    end
  end

  def demonew
    @article = Article.new
    @current_user = session[:user_id] ? User.find(session[:user_id]) : User.new
    @catagories = Catagory.get_all(@current_user.id)
    set_page_title('Demo')
    render :new
  end

  #def demoshow
    #render :show
  #end

  protected
  def set_catagories(user_id)
    @catagories = Catagory.get_all(user_id)
  end

  def init_params
    params[:article][:catagory_id] = 0 if params[:article][:catagory_id].blank?
  end

  def article_params
    params.require(:article).permit(:user, :title, :content, :catagory_id, :picture, :user_id)
  end
end

app/helpers/articles_helper.rb
#encoding: utf-8
module ArticlesHelper
  def owner?
    @owner || @admin
  end

  def admin?
    @admin
  end

  def logo_link
    @logined ? name_path(@user_name) : root_path
  end

  def flash_message
    f = flash.to_hash
    if f.size > 0
      str = f.values.join(", ")
      c = f.has_key?(:alert) ? "danger" : "success"
      content_tag :script, raw( "$(document).ready(function(){$.pnotify({text:\"#{str}\",type:\"#{c}\"})});")   
    end
  end

  def catagory_sidebar(user)
    render partial: 'layouts/catagory', locals: { catagories: @catagories, user_id: user.id}
  end

  def user_information_sidebar(user)
    render partial: 'articles/userinformation', locals: {user: user}
  end

  def catagory_get_name_link(c)
    link_to c.name, id_default?(c.id) ? "#{catagory_path(0)}?user_id=#{c.user_id}" : user_catagory_path(c.user_id, c)
  end

  def catagory_get_delete_link(c)
    id_default?(c.id) ? nil : (link_to "x", catagory_path(c), method:'delete', remote:true, class:'pull-right')
  end

  def catagory_name(article, catagories)
    article.catagory_id == 0 ? link_to("默认分类",user_catagory_path(article.user_id, 0)) : link_to(catagories.find{|c| c.id == article.catagory_id}.name, user_catagory_path(article.user_id,article.catagory_id))
  end

  def id_default?(id)
    id == nil || id ==0 
  end

  def article_width_height
    if new_or_edit?
      "class='article_edit_width'"
    else
      "class='article_normal_width'"
    end
  end

  def page_title_helper
    if @page_title.blank?
      "咕哒网"
    else
      "#{@page_title} | 咕哒网"
    end
  end

  def logined?
    @logined
  end

  def show_comments(comments)
    if comments.size>0
      str = ""
      comments.each_with_index do |c,i|
        str += content_tag :div, "#{c.user_name}: #{c.content}</br>#{c.created_at}", class: 'comment_each' 
      end
      str.html_safe
    else
      nil
    end
  end

  def show_user_head(user = nil, width=nil, version=:head)
    if user.nil?
      return content_tag :i, "", class: 'avatar_image' 
    end

    if user.head.present?
      if owner?
        link_to (get_image_link(user,width,version)), "#upload_head", "data-toggle" => 'modal', "rel" => "popover", "data-content" => '这里可以快速设置你的头像'  
      else
        get_image_link(user,width,version)
      end
    else
      if owner?
        link_to "", "#upload_head", "data-toggle" => 'modal', "rel" => "popover", "data-content" => '这里可以快速设置你的头像', "class" => "avatar_image"  
      else
        content_tag :i, "",class: 'avatar_image' 
      end
    end
  end

  def avatar_url(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar#{gravatar_id}.png?s=250"
  end

  def new_or_edit?
    params[:action].in? %w(edit new create update demonew demoshow)
    #    params[:action] == ('edit' || 'new' || 'create' || 'update')
  end

  def demo?
    params[:action].in? %w(demonew demoshow)
  end

  def jtime(time)
    normal = time.strftime('%Y年%m月%d日')
    regtime = (Time.now-time)
    if regtime < 60
      "刚刚"
    elsif regtime < 3600
      "#{(regtime/60).to_i}分钟前"
    elsif regtime < 86400
      "#{(regtime/3600).to_i}小时前"
    elsif regtime < 2592000
      "#{(regtime/86400).to_i}天前"
    elsif regtime < 31536000
      "#{(regtime/2592000).to_i}个月前"
    else 
      normal
    end
  end

  def get_notifications_count(user_id)
    c = Notification.where("receiver_id=? and readed=0", user_id).count
    if c > 0
      span = (content_tag :span, c, class: 'badge jbadge-info')
      a = link_to span, user_notifications_path(user_id)
      return a
    else
      nil
    end
  end

  def active_class(symbol)
    if symbol.to_s == params[:controller]
      'class=active'
    end
  end

  def active_page_class(page1, page2)
    if page1.id == page2.id
      'class=active'
    end
  end

  def sprite_tag(class_name)
    content_tag :i, '', class:class_name, style:'display:inline-block'
  end

  def get_authentication_status(client,authentication_hash)
    if authentication_hash.nil? || authentication_hash[client].nil?
      link_to "尚未关联", "/auth/#{client}"
    else
      if expires?(authentication_hash[client]['expires']) 
        link_to "已过期,重新授权", "/auth/#{client}"
      else
        content_tag(:span, '已关联 | ') + link_to('取消', user_authentication_path(@user_id, authentication_hash[client]['id']), method:'delete')
      end
    end
  end

  def expires?(timestamp)
    return false unless timestamp
    if timestamp.class == String
      timestamp = timestamp.to_i
    end
    Time.now.to_i - timestamp >= 0
  end

  def get_authentication_info(client,authentication_hash)
    if authentication_hash.nil? || authentication_hash[client].nil?
      link_to "尚未关联", "/auth/#{client}"
    else
      image_tag(authentication_hash[client]['image']) + content_tag(:span,authentication_hash[client]['nickname'], class:'luser_name')  
    end
  end

  private
  def t_to_i(regtime)
    (regtime).to_i
  end

  def get_image_link(user,width=nil,version)
    url = (version) == :origin ? user.head.file.url : user.head.file.send(version).url
    unless width.nil?
      image_tag url, width:"#{width}px"
    else
      image_tag url
    end
  end

  def share_article(article)
    callpartial = false 
    title_str = "分享文章"
    if cookies[:create_article]
      title_str = "文章创建成功,要分享吗?"
      callpartial = true
    end

    if cookies[:update_article]
      title_str = "文章修改成功,要分享吗?"
      callpartial = true
    end
    content = "发表了文章：#{article.title}, \"#{article.content.first(50)}...\" #{article_url(article)}"
    callpartial ? (render partial: 'share', locals: {authentications: Authentication.get_all(@user_id),title: title_str, content: content, article: article}) : nil
  end

  def share_to_image(provider)
    content_tag :i,"", class: "icons_#{provider}", style: "display:inline-block"
  end

  def pic_preview(picture)
    raw "<img class=\"img-polaroid\" data-toggle='pic' src=\"#{picture.file.small.url}\" id='img_#{picture.id}'/>"
  end

  def modal(options = {})
    options= {id:"",button:"确定",header:"", prompt:"", style:""}.merge(options)
    render(layout:"layouts/modal", locals:options) do
      yield
    end
  end
  
  def modal_link(href, str, sclass="btn")
    raw "<a href=\"#{href}\" role=\"button\" class=\"#{sclass}\" data-toggle=\"modal\">#{str}</a>"
  end
end

app/views/articles/_form.html.erb
<% content_for :other_js do %>
  <%= javascript_include_tag 'blog/spine'%> 
  <%= javascript_include_tag "blog/editor" %>
  <%= javascript_include_tag 'blog/picture'%> 

  <style type="text/css">
    body {
      overflow-y:hidden;
    }
  </style>
<%end%>
<% catagories ||= nil %>
<div id="article_edit" >
  <%= simple_form_for article, wrapper: :default, html: {multipart: true, id: 'article_form' } do|f| %> 
    <%= (f.input :catagory_id, collection: catagories, label: false, as: :jcatagory, input_html: {id: "catagories_select"}, wrapper_html: {style: 'display:inline' }) if catagories %> 
    <%= f.input :title, label: false, input_html: {id:'article_title'}, wrapper_html: {style: 'display:inline' }%>
    <% if article.has_attribute?(:subtitle) %>
      <%= f.input :subtitle, label: false, input_html: {id:'article_subtitle'}, wrapper_html: {style: 'display:inline'}, placeholder:'副标题' %>
    <% end %>
    </br>

    <ul class="unstyled" id="form_toolbox">
      <li><a href="#add_catagory_modal" data-toggle='modal' rel='tooltip' title='添加分类'><i class="icon-plus"></i></a> </li>
      <li><a href='javascript:void(0)' data-toggle='preview' id='toggle_preview' rel='tooltip' title='预览'><i class="icon-eye-open"></i> </a></li>
      <li><a href="#draft" data-toggle="modal" rel='tooltip' title='草稿'><i class="icon-pencil"></i></a></li>
      <li></li>
      <li><a href="javascript:void(0)" id='toggle_pic' data-toggle='modal' rel='tooltip' title='图片'><i class="icon-picture"></i></a></li>
      <li><a href="javascript:void(0)" rel='tooltip' id='link_button' title='链接'><i class="icon-link "></i></a></li>
      <li><a href="javascript:void(0)" rel='tooltip' id='strong_button' title='粗体'><i class="icon-bold"></i></a></li>
      <li><a href="javascript:void(0)" rel='tooltip' id='italic_button' title='斜体'><i class="icon-italic"></i></a></li>
      <li><a href="#markdown_hint" data-toggle="modal" rel='tooltip' title='markdown帮助'><i class="icon-question-sign"></i></a></li>
    </ul>

    <div class='ul_content_wrapper'>
      <%= f.input :content, as: :text, label: false, input_html:{rows:0, cols:0, id:'article_content', class:'content_normal_width'}, wrapper_html:{id:'content_wrapper'}%>
      <ul id="ul_showpic" class="unstyled">
        <a href="#upload_pic_modal" class="btn btn-primary" data-toggle='modal' rel='tooltip' title='图片'><i class="icon-upload"></i><span>上传图片</span></a>
      </ul>
    </div>

    <div class="clear"></div>

    <%if demo?%>
      <%= f.button :submit, '发布', class: 'btn-primary span2', disabled: true %>
    <%else%>
      <%= f.button :submit, '发布', class: 'btn-primary span2'%>
    <%end%>
      <a href="#draft" data-toggle="save-draft" class="btn btn-primary" >保存草稿</a>
  <%end%>
</div>

<%= content_for :preview do %>
  <div id="preview_container">
    <div id="preview_toolbar" class="pull-right">
      <div class="btn-group">
        <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
          预览
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li><a href="javascript:void(0)" data-toggle='html'>预览</a></li>
          <li><a href="javascript:void(0)" data-toggle='text'>HTML</a></li>
        </ul>
      </div>
    </div>

    <div id="preview_title"><h1>题目</h1></div>

    <div id="preview_content"></div>

    <div class="clear"></div>
  </div>
<%end%>

<% if catagories %>
  <div class="modal" id="add_catagory_modal">
    <div class="modal-header">
      <button class="close" data-dismiss="modal">×</button>
      <h3>增加分类</h3>
    </div>
    <div class="modal-body">
      <%= simple_form_for Catagory.new(), remote: true, html: {id: 'catagory_form', "data-type" => 'json', class: 'form-horizontal' }   do |f| %>
        <%= f.input :user_id, as: :hidden, input_html: {value: user.try(:id), autocomplete: 'off'}  %>
        <%= f.input :name, label: '分类名称', wrapper_html: {style: "float:left;margin-right:10px"}, input_html: {id: 'catagory_name_input' } %>
        <%= f.submit '确定', class: 'btn btn-primary'  %>
      <% end %>
    </div>
  </div>
<% end %>



<div class="modal" id="draft">
  <div class="modal-header">
    <button class="close" data-dismiss="modal">×</button>
    <h3><span id="draft_username">草稿</span><span class="prompt">(点击显示草稿内容,每3分钟或每输入60个字自动保存,手动保存可以同步到服务器)</span></h3>
  </div>
  <div class="modal-body">
    <ul class="nav nav-tabs" id="draft_tab">
      <li class="active"><a href="#manual_draft" data-toggle="tab">手动</a></li>
      <li><a href="#automatic_draft" data-toggle="tab">自动</a></li>
    </ul>
    <div class='tab-content' id="draft_table_div">
      <div id="manual_draft" class='tab-pane active'></div>
      <div id="automatic_draft" class='tab-pane'>
        <a href="javascript:void(0)" class="btn btn-danger" data-toggle='destroyAll' >清空</a>
      </div>
    </div>
  </div>
</div>

<%= modal(id:"upload_pic_modal", header:"上传图片",prompt:'(一次可选择上传4张图片)',button:nil) do %>
  <div class="drag_to">
    <span class="grey_font">把图片拖动到此处<br />或</span>
    <div class="drop_file btn_in_drag btn btn-primary">点击添加图片</div>
  </div>
  <div class="empty_height"></div>
  <ul id="ul_for_pic" class="show_upload_pic unstyled"></ul>
<%end%>

<%= render "articles/markdown_hint" %>

app/views/articles/_share.html.erb
<%= javascript_include_tag "share" %>
<div class="modal hide" id="ShareModal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3><%= title%></h3>
  </div>
  <div class="modal-body">
    <%= form_tag share_authentications_path do%>
      <% authentications.each do |a|%>
        <%= share_to_image a.provider%>
        <% if a.expires? %>
          <%= link_to "绑定已过期，点击关联", "/auth/#{a.provider}"%> 
        <%else%>
          <%= check_box_tag 'providers[]',a.provider, true%>
        <%end%>
      <%end%>
      <%= hidden_field_tag 'article', article.id %>
      <%= submit_tag "确定", class: 'btn btn-primary pull-right'%>
    <%end%>
  </div>
</div>

app/views/articles/_sidebar.html.erb
<% unless new_or_edit? %>
  <div id="sidebar">
    <div class="sidebar_container ui_container">
      <%= user_information_sidebar(user) %>
    </div>
    <div class="sidebar_container catagory_container">
      <div class="empty_height"></div>
      <%= catagory_sidebar(user) %>
      <div class="empty_height"></div>
    </div>
  </div>
<%end%>

app/views/articles/_signupnew.html.erb
<div id="signup_new">
    <h2>
      恭喜你注册成功！<br/>你可以按照页面的提示再做进一步的设置，或者马上<%= link_to "新建文章", new_article_path %> <br/><br/>
    </h2>
  </div>

<script type="text/javascript" charset="utf-8">
    $(document).ready(function(){
        $(".avatar_image").popover({placement:"right"});
        $(".avatar_image").popover("show");
        $("#article").height($("#sidebar").height());
    });
</script>

app/views/articles/_userinformation.html.erb
<div id="user_information">
  <div id="user_head" >
    <%= show_user_head user %>
    <span><%= user.name %></span>
  </div>
  <div class="empty_height"></div>
  <div id="user_description_div">
    <%= user.description %>
  </div>

  <div class="modal" id="upload_head">
    <div class="modal-header">
      <button class="close" data-dismiss="modal">×</button>
      <h3>快速设置你的头像</h3>
    </div>
    <div class="modal-body">
      <%= simple_form_for user, html: {id: 'upload_head_form', class: 'form-inline', multipart: true }, wrapper: :default do |f| %>
        <%= f.simple_fields_for user.setting do|setting| %>
          <%= setting.input :picture, as: :file, label: false, wrapper_html: {style: "display:inline-block;margin-left:95px; width:50%;"} %>
        <%end%>
        <%= f.button :submit, '确定', class: 'btn-primary' %>
      <%end%>
    </div>
  </div>
</div>
<div class="empty_height"></div>

app/views/articles/edit.html.erb
<%= render partial: 'form', locals: {:edit => true, :title => '修改文章', user: @current_user, article: @article, catagories: @catagories} %> 

app/views/articles/index.html.erb
<div id="articles">
  <% if @signup_new && owner? %>
    <%= render partial: 'articles/signupnew' %> 
  <%else%>
    <% @articles.each_with_index do|a,i| %>
      <div class='article_each'>
        <h1 class='title_h'><%= link_to a.title, article_path(a.id) %></h1>
        <div class='time'>
          <%= jtime a.created_at %>
           | 分类: <%= link_to a.catagory.name, user_catagory_path(a.user_id, a.catagory_id)%>
           | 访问量: <%= a.visit %> 
           <% if a.comments_count.value > 0 %>
             | <%= link_to "评论(#{a.comments_count.value})", "#{article_path(a)}#comment"%> 
           <%end%>
        </div>
        <div class='empty_height'> </div>
        <%= markdown(a.preview) %>

        <%= (link_to '删除', article_path(a), method: 'delete', class: "btn btn-danger pull-left", "data-toggle" => "delete", style:"display:none") if owner?%>  
        <div class="each_buttons pull-right">
          <%= link_to '阅读全文', article_path(a.id), class: "article_link_button btn btn-primary btn-small" %>  
          <%= (link_to '修改', edit_article_path(a), class: "article_link_button btn btn-primary btn-small") if owner? %>  
          <%= link_to "评论", article_path(a)+"#comment", class: "article_link_button btn btn-primary btn-small"%> 
        </div>
        <div class="clear"></div>
      </div>
      <%unless (i+1) == @articles.size %>
        <div class="empty_height"></div>
        <div class="empty_height"></div>
        <div class="empty_height"></div>
      <%end%>
    <% end %>
  <%end%>
  <%= paginate @articles, window:2 %>
</div>

<% unless new_or_edit? %>
  <div id="switch_sidebar_button">
    <a href="javascript:void(0)"><i class="icon-chevron-right"></i></a>
  </div>
<%end%>

app/views/articles/new.html.erb
<%= render partial: 'form', locals: {new: true, title: '新文章', user: @current_user, article: @article, catagories: @catagories} %> 

app/views/articles/show.html.erb
<% content_for :other_js do %>
  <%= javascript_include_tag 'blog/spine'%> 
  <%= javascript_include_tag "blog/comment" %>
<%end%>

<div id="articles">
  <div class="article_each">
    <h1 class="title_h"><%= @article.title %></h1>
    <div class="time">
      发表于:<%= jtime @article.created_at %> | 访问量:<%= @article.visit %> | 分类:<%= catagory_name(@article,@catagories) %>
    </div>
    <div id="article_show_content">
      <p><%= markdown(@article.content) %></p>
      <%= (image_tag @article.pictures[0].file.preview.url) if @article.pictures.size > 0  %>
      <div class="each_buttons">
        <%= (link_to '修改', edit_article_path(@article)) if owner? %> 
      </div>
    </div>
    <div class="empty_height"></div>
  </div>
</div>

<% unless new_or_edit? %>
  <div id="switch_sidebar_button">
    <a href="javascript:void(0)"><i class="icon-chevron-right"></i></a>
  </div>
<%end%>

<%= content_for :comment do%>
  <div class="empty_height"></div>
  <div id="comment" class="article_normal_width">
    <div id="comments">
    </div>
  </div>
<% end %>

<%= share_article(@article)%>