config/routes.rb
GuDa::Application.routes.draw do
  root :to => 'blog#index'
  get "blog" => 'blog#index'
  get "blog/logout" => "blog#logout", as: :logout
  get "/auth/:provider/callback", :to => "authentications#create"
  get "/auth/failure", :to => "authentications#index"
  get "/articles/demonew", :to => "articles#demonew"
  get "/articles/demoshow", :to => "articles#demoshow"

  #scope 'blog' do
  resources :users do
    resources :articles do
      resources :comments
    end
    resources :drafts
    collection do 
      post :login
      post :new
      get :new
    end
    resources :notifications, :only => [:index, :show, :destroy] 
    resources :settings
    resources :authentications
    resources :catagories
    resources :pictures
  end
 
  resources :pages
  resources :pictures, :only => [:create, :destroy]
  resources :admins
  resources :articles do
    resources :comments
  end
  resources :drafts
  resources :catagories
  resources :tags
  resources :notifications
  resources :authentications do
    collection do
      post :share
    end
  end
  post "users/login" => 'users#login', :as => :login 

#  end
  get ':user_id', :to => 'articles#index', :as => :name
  #match ':controller(/:action(/:id(.:format)))'  
end

app/models/notification.rb
#encoding: utf-8
class Notification < ActiveRecord::Base
  belongs_to :senderable, polymorphic: true  
  belongs_to :user, foreign_key: :receiver_id
  #  validates :content, :presence => {message:"内容不能为空"} 
  validates :senderable, presence: {message:"不能没有发送者"}
  validates :receiver_id, presence: {message:'不能没有接收者'}

  def self.get_all(user_id)
    ns = includes(senderable: [:user, :article]).where("receiver_id=?", user_id).order("created_at desc")
    ns.update_all(readed: true)
    ns
  end

  def self.unread_count(user_id)
    where("receiver_id=? and readed=0 ", user_id).count
  end
end

app/controllers/notifications_controller.rb
#encoding: utf-8
class NotificationsController < ApplicationController
  before_filter :check_login
  before_filter :check_session
  def index
    respond_to do|format|
      format.html do
        @notifications = Notification.get_all(params[:user_id])
        render layout: 'acount_setting'
      end
      format.json {render json: {count:Notification.unread_count(params[:user_id]), path:user_notifications_path(params[:user_id])}}
    end
  end

  def show
  end

  def destroy
    n = Notification.delete(params[:id])
    flash[:error] = '删除失败' if n == 0
    redirect_to user_notifications_path(@user_id)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/index.html.erb
<div id="eu_form_div" class="tab-pane active">
  <div id="notifications">
    <% if @notifications.size == 0%>
      <div class='notification_each'>
        当前用户暂无通知消息
      </div>
      <div class='empty_height'></div>
    <%else%>
      <% @notifications.each do|n|%>
        <div class="notification_each">
          <div class='pull-right'>
            <%= ( link_to "回复", article_path(n.senderable.article_id)+"#comments", class: 'btn btn-primary' ) if n.senderable %> 
            <%= link_to "删除", notification_path(n), method: 'delete', class: 'btn btn-danger' %> 
          </div>     
          <div class='head_div'>
            <%= show_user_head(n.senderable.try(:user), nil, :small)%>
          </div>
          <div class="pull-left notification_content">
            <%= markdown(n.content)%>
          </div>
          <div class="empty_height"></div>
        </div>   
      <% end %>

    <%end%>
  </div>
</div>