config/routes.rb
GuDa::Application.routes.draw do
  root :to => 'blog#index'
  get "blog" => 'blog#index'
  get "blog/logout" => "blog#logout", as: :logout
  get "/auth/:provider/callback", :to => "authentications#create"
  get "/auth/failure", :to => "authentications#index"
  get "/articles/demonew", :to => "articles#demonew"
  get "/articles/demoshow", :to => "articles#demoshow"

  #scope 'blog' do
  resources :users do
    resources :articles do
      resources :comments
    end
    resources :drafts
    collection do 
      post :login
      post :new
      get :new
    end
    resources :notifications, :only => [:index, :show, :destroy] 
    resources :settings
    resources :authentications
    resources :catagories
    resources :pictures
  end
 
  resources :pages
  resources :pictures, :only => [:create, :destroy]
  resources :admins
  resources :articles do
    resources :comments
  end
  resources :drafts
  resources :catagories
  resources :tags
  resources :notifications
  resources :authentications do
    collection do
      post :share
    end
  end
  post "users/login" => 'users#login', :as => :login 

#  end
  get ':user_id', :to => 'articles#index', :as => :name
  #match ':controller(/:action(/:id(.:format)))'  
end

app/views/layouts/_breadcrumbs.html.erb
<% unless @breadcrumbs.blank? %>
  <ol class="breadscrum">
    <% @breadcrumbs.each_with_index do |b, i|%>
        <li <%= raw("class='active'") if i == @breadcrumbs.size - 1 %>>
          <i class="icon-chevron-right"></i>
          <%= b %>
        </li>
    <%end%>
  </ol>
<%end%>

app/views/layouts/_catagory.html.erb
<div id="catagory">
  <span class="strong sidebar_title">分类</span>
  <%= (link_to "增加", "#add_catagory_modal", "data-toggle"=>'modal', class:'pull-right') if owner? %> 
  <div id="catagories">
    <%= render partial: 'catagories/each', locals: {catagories:catagories}  unless @catagories.nil? %>
  </div>
</div>

<div class="modal" id="add_catagory_modal">
  <div class="modal-header">
    <button class="close" data-dismiss="modal">×</button>
    <h3>增加分类</h3>
  </div>
  <div class="modal-body">
    <%= simple_form_for Catagory.new(), remote: true, html: {id: 'catagory_form', "data-type" => 'json', class: 'form-horizontal' } do |f| %>
      <%= f.input :user_id, as: :hidden, input_html: {value: user_id, autocomplete: 'off'}  %>
      <%= f.input :name, label: '分类名称', wrapper_html: {style: "float:left;margin-right:10px"}, input_html: {id: 'catagory_name_input' } %>
      <%= f.submit '确定', class: 'btn btn-primary'  %>
    <% end %>
  </div>
</div>

app/views/layouts/_foot.html.erb
<style>
  #foot_id {
    margin: 10px auto 0 auto;
    width: 676px;
  }

  #foot_ul li {
    list-style: none;
    float: left;
    color:white;
  }
</style>

<div id="foot_id" class="container">
  <ul id="foot_ul">
    <li> <%= link_to 'demo', url_for(controller: 'articles', action: 'demonew')%> | </li>
    <li> <%= link_to 'markdown', page_path('what-is-markdown') %> | </li>
    <li> <%= link_to '反馈', 'javascript:void(0)'%> | </li>
    <li> <%= link_to '关于', page_path('what-is-gu-da')%> | </li>
    <li> <%= link_to '源码', 'https://github.com/reducm/gu-da'%> </li>
  </ul>
</div>

app/views/layouts/_meta_favicon.html.erb
<%= favicon_link_tag '/favicon.png', :type => 'image/png' %>  
<meta name="description" content="咕哒网是一个以发布原创博客为主的网站，提供以Markdown语法为主简单专注的方式供用户生产内容。我们的宗旨是要成为一个令用户专注于学习与工作的好工具">

app/views/layouts/_modal.html.erb
<div class="modal hide fade" id="<%= id || nil %>" style="<%= style || nil%>">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
    <h3><%= header || nil %><span class="prompt"><%= prompt || nil %></span></h3>
  </div>
  <div class="modal-body">
    <%= yield %>
  </div>
  <% if button %> 
    <div class="modal-footer">
      <a href="#" class="btn btn-primary"><%= button %></a>
    </div>
  <% end %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" id="navbar" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="<%= logo_link %>" class="navbar-brand">
        <i class="logo_tiny"></i>
        <span class='gu'>咕</span>哒
      </a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right navtool">
        <% unless @user_name.blank? %>
          <li id="notification_li"><%= get_notifications_count(@user_id) %></li>
          <% if logined? %>
            <li> <a href="<%= new_article_path() %>"><i class="icon-edit"></i></a> </li>
          <% end %>

            <% if @current_user && @current_user.id %>
              <li><%= ( link_to  raw("<i class='icon-rss'></i>"), user_articles_path(@current_user)+".atom", class: 'rss' ) %></li>
            <% end %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="icon-cogs"></i>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to '设置', edit_user_path(@user_id) %> </li>
              <li><%= link_to "关于", pages_path %></li>
              <li><%= link_to "退出", logout_path %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to '登录', blog_path %> </li>
          <li><%= link_to '注册', new_user_path %> </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav> 

app/views/layouts/_setting_nav.html.erb
<li <%= active_class(:users) %> > <%= link_to "个人资料", edit_user_path(user_id) %> </li>
<li <%= active_class(:notifications) %> > <%= link_to "消息管理", user_notifications_path(user_id)%></li>
<li <%= active_class(:authentications) %> > <%= link_to "社交授权", user_authentications_path(user_id)%></li>
<%if admin?%>
  <li <%= active_class(:admins) %> > <%= link_to "管理员", admins_path %></li>
<%end%>

app/views/layouts/acount_setting.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title_helper %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "pnotify" %>
    <%= javascript_include_tag "user" %>
    <%= yield :other_js %>
    <%= csrf_meta_tags %>
    <%= render partial: "layouts/meta_favicon" %>
  </head>
  <body>
    <%= render partial: 'layouts/nav' %> 

    <div id="flash"><%= flash_message %></div>

    <div class="container container_trans row" id="container">

      <div id="edit_user_div">
        <div id="edit_user_left">
          <ul class="nav nav-list nav-stacked nav-tabs bs-docs-sidenav ">
            <% unless params[:controller] == 'pages' %>
              <%= render partial:"layouts/setting_nav", locals:{user_id: @user_id} %>
            <% else %>
              <%= render partial:"pages/pages_nav", locals:{pages:@pages, page:@page, user_id:@user_id} %>
            <% end %>
          </ul>
        </div>
        <div id="edit_user_right" class="tab-content">
          <%= yield %>
        </div>
      </div>

    </div>
    <%= content_tag :div, id:'guda', data:{
      guda: {
        user_id:@user_id || 0, 
        article_id: @article.try(:id) || nil,
        action:params[:action], 
        controller:params[:controller], 
        controllers:[], 
        isLogined: logined?
      }
      } do %>
    <% end%>
    <script>window.action="<%= params[:action]%>"</script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title || '咕哒网' %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "pnotify" %>
    <%= javascript_include_tag "user" if params[:controller] == 'users'%>
    <%= yield :other_js %>
    <%= csrf_meta_tags %>
    <%= render partial: "layouts/meta_favicon" %>
  </head>
  <body>


    <div id="flash"><%= flash_message %></div>

    <%= render partial: 'layouts/nav' %>
    <div class="container" id="container">
      <div id="jas">
        <%= yield %>
      </div>
    </div>
    <%= content_tag :div, id:'guda', data:{
      guda: {
        user_id:@user_id || 0, 
        article_id: @article.try(:id) || nil,
        action:params[:action], 
        controller:params[:controller], 
        controllers:[], 
        isLogined: logined?
      }
      } do %>
    <% end%>
  </body>
</html>

app/views/layouts/article.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title_helper %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "pnotify" %>
    <%= javascript_include_tag "article" %>
    <%= yield :other_js %>
    <%= csrf_meta_tags %>
    <%= ( auto_discovery_link_tag :atom, user_articles_url(@current_user)+".atom" ) if @current_user && !@current_user.new_record?%>
    <%= render partial: "layouts/meta_favicon" %>
  </head>
  <body>

    <%= render partial: 'layouts/nav' %> 

    <div id="flash"><%= flash_message %></div>

    <div class="container container_trans" id="container">

      <div id="article" <%= raw article_width_height %>>
        <%= yield %> 
      </div>

      <div id="preview">
        <%= yield :preview %> 
      </div>
      <% if new_or_edit? %> 
        <div class="clear"></div>
      <% end %>
      <%= render partial: 'articles/sidebar', locals: {user: @current_user } %>

      <%= yield :comment %>
    </div>
    <% unless new_or_edit? %>
      <%= render partial: 'layouts/foot' %>
    <%end%>
    <br/ >
    <%= content_tag :div, id:'guda', data:{
        guda: {
          user_id:session[:user_id] || 0, 
          user_head: (@user && @user.head ? @user.head.file.url : nil),
          user_name:session[:user_name] || 'DemoUser', 
          article_id: @article.try(:id) || nil,
          action:params[:action], 
          controller:params[:controller], 
          controllers:[], 
          isLogined: logined?
        }
      } do %>
    <% end%>
  </body>
</html>